#reference: http://www.appveyor.com/docs/appveyor-yml

version: 0.0.1.{build}-beta

branches: 
  only:
   - master
  
os: Windows Server 2012
   
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: false  
  
configuration: Release

build:
  project: src\PhoenixSystem.Monogame.sln
  publish_nuget: true
  
before_build:
  nuget restore src\PhoenixSystem.Monogame.sln

artifacts:
  - path: out\*.nupkg